
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../touch-2.4/src",
  "Ext.data.ProxyMgr": "../touch-2.4/src/app/Application.js",
  "Ext.device.Purchases.Product": "../touch-2.4/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../touch-2.4/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../touch-2.4/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../touch-2.4/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../touch-2.4/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../touch-2.4/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../touch-2.4/src/draw/engine/SvgContext.js",
  "Images": "app",
  "Images.store.Images": "app/store/Images.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Images.controller.Main": [],
  "Images.model.Image": [],
  "Images.store.Images": [],
  "Images.view.CapturePicture": [],
  "Images.view.Main": [],
  "Images.view.ImageForm": [],
  "Images.view.ImagesList": []
});
Ext.ClassManager.addNameAliasMappings({
  "Images.controller.Main": [],
  "Images.model.Image": [],
  "Images.store.Images": [
    "store.users"
  ],
  "Images.view.CapturePicture": [
    "widget.capturepicture"
  ],
  "Images.view.Main": [
    "widget.main"
  ],
  "Images.view.ImageForm": [
    "widget.imageform"
  ],
  "Images.view.ImagesList": [
    "widget.userslist"
  ]
});
